//generated file: C:/Users/SyncthingServiceAcct/QR_Sync/templateprojectwev\include\templateprojectwev_cp\Config.hpp
//**********************************************************************
//this is an auto-generated file using the template file located in the directory of C:\QR_Sync\CgenMin\CgenMin\FileTemplates\Files
//ONLY WRITE CODE IN THE UserCode_Section BLOCKS
//If you write code anywhere else,  it will be overwritten. modify the actual template file if needing to modify code outside usersection blocks.

//############################################### 
//this is an autogenerated file using cgen's macro2 command. Dont modify this file here unless it is in user sections 
//###############################################

#pragma once


//####################################
//AE Settings
//####################################

#define AOPRIORITYLOWEST 5
#define AOPRIORITYMEDIUM 10
#define AOPRIORITYHIGHEST 29
#define NUMOFACTIVEOBJECTS 3
#define HIGHEST_NUM_OF_EVT_INSTANCES 4
#define RUNNING_TARGET defaultTest








//####################################
//AO defines
//####################################

#define Event0 QREventMSG
#define Event0Size 0


#define Event0 QREventMSG
#define Event0Size 0

#define Event0 QREventMSG
#define Event0Size 0

#define Signal0 QREventSRV

#define Event0 QREventMSG
#define Event0Size 0

#define Signal0 QREventSRV

#define Event0 QREventMSG
#define Event0Size 0


#define Signal0 QREventSRV

#define Event0 QREventMSG
#define Event0Size 0




//####################################
//AE hal defines
//####################################







#define PROJECT_NAME templateprojectwev


#include <string>

#include <cereal/archives/xml.hpp>
#include <cereal/archives/json.hpp>


//UserCode_Sectionc
//UserCode_Sectionc_end

namespace templateprojectwev_cp {
 

             class QR_Settings
             {
             public: 

               //put the variables you want to have as settings
               //for example
               //int size1;
               //std:string someothersetting
               int32_t size1;std::string id;

               // This method lets cereal know which data members to serialize.
               template<class Archive>
               void serialize(Archive & archive)
               {

                 //you need to now set these variables in the archive. For example
                 //for example:
                 //archive(CEREAL_NVP(id),CEREAL_NVP(size1), CEREAL_NVP(someothersetting));
                 archive(CEREAL_NVP(size1), CEREAL_NVP(id));

               }
             };



//UserCode_Sectiond
//UserCode_Sectiond_end

#ifdef ROS2_PROJECT
extern QR_Settings QRSettings;
#endif

}











 

