################################################ 
#this is an autogenerated file using cgen's macro2 command. Dont modify this file here unless it is in user sections 
################################################

set(EXE_TARGET_SELECTED defaultTestRos)

####################################
#Library Target
#################################### 
QR_CreateTarget_ROS2Library()
#templateprojectwev_ROSlib is being linked to project templateprojectwev target templateprojectwev_cp::templateprojectwev_CPPlib
target_link_libraries(templateprojectwev_ROSlib templateprojectwev_cp::templateprojectwev_CPPlib) 


QR_target_done()



####################################
#defaultTestRos EXE Target
####################################
if(${EXE_TARGET_SELECTED} STREQUAL defaultTestRos)
    
	QR_CreateTarget_ROS2IntegrationEXE(
	NAME_OF_TARGET defaultTestRos
	IS_FOR_COMPOSABLES OFF
	WantToGenerateMain FALSE
	FOR_REAL_AO World)
	
	#QR_target_link_to_ROSLibrary(MODULE_NAME ${MODULE_NAME})
	QR_target_done() 
	
	#defaultTestRos is being linked to project templateprojectwev target templateprojectwev_ROSlib
target_link_libraries(defaultTestRos templateprojectwev_ROSlib) 


	
endif()








  






 







  









 

