################################################ 
#this is an autogenerated file using cgen's macro2 command. Dont modify this file here unless it is in user sections 
################################################

set(EXE_TARGET_SELECTED defaultTest)

####################################
#Library Target
####################################  
QR_CreateTarget_CPPLibrary()

QR_target_done()



####################################
#defaultTest EXE Target
####################################
if(${EXE_TARGET_SELECTED} STREQUAL defaultTest)
    QR_CreateTarget_CPPIntegrationEXE(NAME_OF_TARGET defaultTest)
	QR_target_link_to_CPPLibrary(MODULE_NAME ${MODULE_NAME})
	QR_target_done() 
endif()








QR_CreateTarget_UnitTests()
QR_target_done()









 

