//############################################### 
//this is an autogenerated file using cgen's macro2 command. Dont modify this file here unless it is in user sections 
//###############################################



using CgenMin.MacroProcesses;
using CgenMin.MacroProcesses.QR;
using CodeGenerator.MacroProcesses.AESetups;
using System;
using System.Collections.Generic;
using System.Runtime;

namespace templateprojectwevProject
{


  


    // [QREnum(typeof(templateprojectwev))]
    // public enum MoveResponse
    // {
        // SUCCESS = 0,
        // OBJECT_ALREADY_THERE = 1,
        // OBJECT_IMMOVABLE = 2,
        // CELL_OUT_OF_BOUNDS = 3,
        // CELL_DESTROYED = 255
    // }
 
      

    // public class World : AOSurrogateNode<World>
    // {
        // [SurrogateData(false)]
        // public Int32 numofgameobjects { get; set; }

        // public World(string instanceName, bool isSurrogate) : base(instanceName, isSurrogate)
        // {
        // }

        // [SurrogateServiceFunction]
        // public MoveResponse MoveObject(Gameobject objToMove, Move move)
        // {
            // return MoveResponse.SUCCESS;
        // } 

        // [SurrogateServiceFunction]
        // public AddObjectResponse AddObjectToWorld(Gameobject objToMove, int posy, int posx)
        // {
            // return AddObjectResponse.SUCCESS;
        // }



        // public override List<ROSTimer> SetAllTimers()
        // {
            // return new List<ROSTimer>()
            // { 
            // };
        // }

        // public override List<ROSPublisher> SetAllPublishers()
        // {
            // return new List<ROSPublisher>()
            // { 
            // };
        // }

        // public override List<ROSSubscriber> SetAllSubscribers()
        // {
            // return new List<ROSSubscriber>()
            // { 
            // };
        // }
    // }

    // public class TestSimple : AONode<TestSimple>
    // { 

        // public TestSimple(string instanceName) : base(instanceName)
        // {
        // }

        // [ServiceFunction]
        // public int AddTwoNumbers(int a, int b)
        // {
            // return 0;
        // }

        // [ServiceFunction]
        // public string GiveName()
        // {
            // return "";
        // }  
        
        // public override List<ROSTimer> SetAllTimers()
        // {
            // return new List<ROSTimer>()
            // {
                // new ROSTimer("testTimer", 1000)
            // };
        // }
         
        // public override List<ROSPublisher> SetAllPublishers()
        // {
            // return new List<ROSPublisher>()
            // {
                // ROSPublisher.CreatePublisher("pub1", new QREventMSGTemplate<int>("SomeTestEvent", "somesize"), true)
            // };
        // }
        // public override List<ROSSubscriber> SetAllSubscribers()
        // {
            // return new List<ROSSubscriber>()
            // {
            // };
        // } 
     
    // } 


    // fix QRSettings issue., generate main.cpp file, finish event subs/pubs then move on to next step

    public class templateprojectwev : QRProject
    {
         
        public class templateprojectwevSettings : TargetSettings
        {
            public string id { get; set; } 
        }


        protected override QRTarget_cpLib InitCPPLibrary()
        {
            return new QRTarget_cpLib(templateprojectwev.TargetCode_if);
        }

        protected override QRTarget_RosLib InitROSLibrary()
        {
            return new QRTarget_RosLib(templateprojectwev.TargetCode_cppLibrary);
        }

        protected override QRTarget_IF InitIFLibrary()
        {
            return new QRTarget_IF();
        }

        public override List<TargetSettingsFile> GetTargetSetting()
        {
            List<TargetSettingsFile> ret = new List<TargetSettingsFile>() { 
            // new TargetSettingsFile( "MySetting1", new templateprojectwevSettings(){  id = "somename"})
            };
            return ret;
        } 
         


        [QRTarget_cpEXE(templateprojectwev.TargetCode_if)]
        public void defaultTest()
        {

            // QREventMSG qREventMSG = new QREventMSG("testMSG", new FunctionArgs<Int64>("var1"), new FunctionArgs<Int64>("var2")); 
            // World world = new World("WorldNode", true);  
             
        }


        [QRTarget_RosEXE(templateprojectwev.TargetCode_if, templateprojectwev.TargetCode_rqtLibrary)]
        public void defaultTestRos()
        {  

        }
 

        protected override string _GetDirectoryOfLibrary()
        {
            return @"templateprojectwev";
        }
 
        protected override List<string> _GetAnyAdditionalIncludeDirs()
        {
            return new List<string>() { };
        }

        protected override List<string> _GetAnyAdditionalSRCDirs()
        {
            return new List<string>() { };
        }


        public const string TargetCode_cppLibrary = "templateprojectwev:cpp_library";
        public const string TargetCode_rqtLibrary = "templateprojectwev:rosqt_library";
        public const string TargetCode_if = "templateprojectwev:IF";
    }



}