################################################ 
#this is an autogenerated file using cgen's macro2 command. Dont modify this file here unless it is in user sections 
################################################

QR_initialize_interfaces()




QR_done_creating_interfaces()
