//generated file: C:/Users/SyncthingServiceAcct/QR_Sync/templateprojectwev\rosqt\src\defaultTestRos_QRmain.cpp
//**********************************************************************
//this is an auto-generated file using the template file located in the directory of C:\QR_Sync\CgenMin\CgenMin\FileTemplates\Files
//ONLY WRITE CODE IN THE UserCode_Section BLOCKS
//If you write code anywhere else,  it will be overwritten. modify the actual template file if needing to modify code outside usersection blocks.

//############################################### 
//this is an autogenerated file using cgen's macro2 command. Dont modify this file here unless it is in user sections 
//###############################################


#include "rclcpp/rclcpp.hpp"




int main(int argc, char **argv) {
    int result = 1;


    rclcpp::shutdown();
    return result;
}


//UserCode_Sectionmain3
//UserCode_Sectionmain3_end






